---
apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: source
  namespace: rust-rest-build
spec:
  type: git
  params:
    - name: url
      value: https://github.com/pabrahamsson/rust-rest.git
---
apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: image
  namespace: rust-rest-build
spec:
  type: image
  params:
    - name: url
      value: image-registry.openshift-image-registry.svc:5000/rust-rest-build/rust-rest:latest
---
apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: image-dev
  namespace: rust-rest-build
spec:
  type: image
  params:
    - name: url
      value: image-registry.openshift-image-registry.svc:5000/rust-rest-dev/rust-rest:latest
