kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pipeline-ws1
  namespace: rust-rest-build
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
